# Generated by Django 4.1.5 on 2023-01-09 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCNPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('razao', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('avenida_rua', models.CharField(max_length=450, verbose_name='Avenida/Rua')),
                ('endereco', models.CharField(max_length=450, verbose_name='Endereço')),
                ('numero', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=90, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=80, verbose_name='Bairro')),
                ('municipio', models.CharField(max_length=60, verbose_name='Municipio')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('cep', models.CharField(max_length=8, verbose_name='Cep')),
                ('nome_cliente', models.CharField(max_length=50, verbose_name='Nome Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='BaseInfoContratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cliente', models.CharField(max_length=5, verbose_name='Cod. Cliente')),
                ('contrato', models.CharField(max_length=65, verbose_name='Contrato')),
                ('cargo', models.CharField(max_length=65, verbose_name='Cargo')),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor Hora')),
                ('data_fim_cto', models.CharField(max_length=10, verbose_name='Data Fim do Contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Competencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(max_length=7, verbose_name='Competência')),
                ('testelogico', models.CharField(max_length=1, verbose_name='Teste')),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_de_modificacao', models.DateField(auto_now=True, verbose_name='Data de Modificação')),
                ('tipo_de_faturamento', models.CharField(choices=[('FATURAMENTO HORAS', 'FATURAMENTO HORAS'), ('FATURAMENTO FG', 'FATURAMENTO FG'), ('FATURAMENTO REPACTUAÇÃO', 'FATURAMENTO REPACTUAÇÃO')], max_length=150, verbose_name='Tipo de Faturamento')),
                ('quantidade_hora', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Quantidade de Horas')),
                ('quantidade_hora2', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Quantidade de Horas 2')),
                ('quantidade_hora3', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Quantidade de Horas 3')),
                ('quantidade_hora4', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Quantidade de Horas 4')),
                ('quantidade_hora5', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Quantidade de Horas 5')),
                ('quantidade_hora6', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Quantidade de Horas 6')),
                ('quantidade_hora7', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Quantidade de Horas 7')),
                ('quantidade_hora8', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Quantidade de Horas 8')),
                ('baseinfocontratos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.baseinfocontratos')),
                ('baseinfocontratos2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_2', to='core.baseinfocontratos')),
                ('baseinfocontratos3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_3', to='core.baseinfocontratos')),
                ('baseinfocontratos4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_4', to='core.baseinfocontratos')),
                ('baseinfocontratos5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_5', to='core.baseinfocontratos')),
                ('baseinfocontratos6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_6', to='core.baseinfocontratos')),
                ('baseinfocontratos7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_7', to='core.baseinfocontratos')),
                ('baseinfocontratos8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_8', to='core.baseinfocontratos')),
                ('cnpj_da_nota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cnpj_da_nota', to='core.basecnpj')),
                ('competencia_nota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.competencias')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
