# Generated by Django 4.1.5 on 2023-01-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinfocontratos',
            name='data_inicio_cto',
            field=models.DateField(default='2023-12-01', max_length=10, verbose_name='Data Inicio do Contrato'),
            preserve_default=False,
        ),
    ]
