# Generated by Django 4.1.5 on 2023-01-23 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_baseinfocontratos_data_inicio_cto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseinfocontratos',
            name='data_fim_cto',
        ),
    ]
