# Generated by Django 4.1.5 on 2023-01-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_baseinfocontratos_data_fim_cto'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecnpj',
            name='tipo_de_servico',
            field=models.CharField(default='17.05', max_length=5, verbose_name='Tipo de Serviço'),
            preserve_default=False,
        ),
    ]
