# Generated by Django 4.1.5 on 2023-02-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_basecnpj_tipo_de_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecnpj',
            name='iss',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=4, verbose_name='Número'),
            preserve_default=False,
        ),
    ]
