# Generated by Django 4.1.5 on 2023-02-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_basecnpj_iss'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecnpj',
            name='unidade',
            field=models.CharField(default='Teste', max_length=55, verbose_name='Unidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basecnpj',
            name='iss',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='ISS'),
        ),
    ]
