# Generated by Django 4.1.5 on 2023-02-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_basecnpj_unidade_alter_basecnpj_iss'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinfocontratos',
            name='contrato_ativo',
            field=models.BooleanField(default=True, verbose_name='Contrato Ativo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseinfocontratos',
            name='data_inicio_cto',
            field=models.DateField(max_length=10, verbose_name='Data Inicio do Contrato no Sistema'),
        ),
    ]
