# Generated by Django 4.1.5 on 2023-02-08 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_baseinfocontratos_contrato_ativo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecnpj',
            options={'ordering': ['uf', 'nome_cliente', 'unidade']},
        ),
        migrations.AlterModelOptions(
            name='baseinfocontratos',
            options={'ordering': ['cod_cliente', 'contrato', 'cargo']},
        ),
        migrations.AlterField(
            model_name='basecnpj',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='baseinfocontratos',
            field=models.ForeignKey(blank=True, limit_choices_to={'contrato_ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.baseinfocontratos'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='baseinfocontratos2',
            field=models.ForeignKey(blank=True, limit_choices_to={'contrato_ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_2', to='core.baseinfocontratos'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='baseinfocontratos3',
            field=models.ForeignKey(blank=True, limit_choices_to={'contrato_ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_3', to='core.baseinfocontratos'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='baseinfocontratos4',
            field=models.ForeignKey(blank=True, limit_choices_to={'contrato_ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_4', to='core.baseinfocontratos'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='baseinfocontratos5',
            field=models.ForeignKey(blank=True, limit_choices_to={'contrato_ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_5', to='core.baseinfocontratos'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='baseinfocontratos6',
            field=models.ForeignKey(blank=True, limit_choices_to={'contrato_ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_6', to='core.baseinfocontratos'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='baseinfocontratos7',
            field=models.ForeignKey(blank=True, limit_choices_to={'contrato_ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_7', to='core.baseinfocontratos'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='baseinfocontratos8',
            field=models.ForeignKey(blank=True, limit_choices_to={'contrato_ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_8', to='core.baseinfocontratos'),
        ),
    ]
