# Generated by Django 4.1.5 on 2023-02-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_basecnpj_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='texto_livre',
            field=models.CharField(default='TESTE', max_length=1625, verbose_name='Texto Livre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notas',
            name='tipo_de_faturamento',
            field=models.CharField(choices=[('FATURAMENTO HORAS', 'FATURAMENTO HORAS'), ('FATURAMENTO FG', 'FATURAMENTO FG'), ('FATURAMENTO REPACTUAÇÃO E REQUILIBRIO', 'FATURAMENTO REPACTUAÇÃO E REQUILIBRIO'), ('FATURAMENTO OUTROS', 'FATURAMENTO OUTROS')], max_length=150, verbose_name='Tipo de Faturamento'),
        ),
    ]
