# Generated by Django 4.1.5 on 2023-02-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notas_texto_livre_alter_notas_tipo_de_faturamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='total_valor_outros',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=25, verbose_name='Total Valor Outros'),
            preserve_default=False,
        ),
    ]
