# Generated by Django 4.1.5 on 2023-02-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notas_total_valor_outros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='texto_livre',
            field=models.CharField(blank=True, max_length=1625, null=True, verbose_name='Texto Livre'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='total_valor_outros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='Total Valor Outros'),
        ),
    ]
