# Generated by Django 4.1.5 on 2023-02-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_notas_texto_livre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecnpj',
            name='tipo_de_cliente',
            field=models.CharField(choices=[('LOG', 'LOG'), ('MOT', 'MOT'), ('DISTRIBUIÇÃO', 'DISTRIBUIÇÃO'), ('PRIVADOS', 'PRIVADOS'), ('OUTROS', 'OUTROS')], default='LOG', max_length=150, verbose_name='Tipo de Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notas',
            name='quantidade_hora',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Quantidade de Horas'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='quantidade_hora2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Quantidade de Horas 2'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='quantidade_hora3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Quantidade de Horas 3'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='quantidade_hora4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Quantidade de Horas 4'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='quantidade_hora5',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Quantidade de Horas 5'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='quantidade_hora6',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Quantidade de Horas 6'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='quantidade_hora7',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Quantidade de Horas 7'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='quantidade_hora8',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Quantidade de Horas 8'),
        ),
    ]
