# Generated by Django 4.1.5 on 2023-02-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_notas_porcentagem_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='porcentagem_ans',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Porcentagem ANS'),
        ),
    ]
