# Generated by Django 4.1.5 on 2023-03-01 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_notas_porcentagem_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='competencia_nota_ans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencia_nota_ans', to='core.competencias'),
        ),
    ]
