# Generated by Django 4.1.5 on 2023-03-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_notas_competencia_nota_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='porcentagem_ans',
            field=models.DecimalField(blank=True, decimal_places=2, error_messages={'max_digits': 'Certifique-se de que tenha digitado o valor correto de porcentagem na ANS'}, max_digits=3, null=True, verbose_name='Porcentagem ANS'),
        ),
    ]
