# Generated by Django 4.1.5 on 2023-03-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_notas_porcentagem_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='quantidade_hora',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='Quantidade de Horas'),
        ),
    ]
