# Generated by Django 4.1.5 on 2023-03-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_notas_quantidade_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='quantidade_hora',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Quantidade de Horas'),
        ),
    ]
