# Generated by Django 4.1.5 on 2023-03-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_notas_quantidade_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='quantidade_hora',
            field=models.DecimalField(blank=True, decimal_places=4, error_messages={'max_digits': 'Valor Digitado passa de 100.000,00 horas verifique se digitou corretamente'}, max_digits=10, null=True, verbose_name='Quantidade de Horas'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='quantidade_hora2',
            field=models.DecimalField(blank=True, decimal_places=4, error_messages={'max_digits': 'Valor Digitado passa de 100.000,00 horas verifique se digitou corretamente'}, max_digits=10, null=True, verbose_name='Quantidade de Horas 2'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='quantidade_hora3',
            field=models.DecimalField(blank=True, decimal_places=4, error_messages={'max_digits': 'Valor Digitado passa de 100.000,00 horas verifique se digitou corretamente'}, max_digits=10, null=True, verbose_name='Quantidade de Horas 3'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='quantidade_hora4',
            field=models.DecimalField(blank=True, decimal_places=4, error_messages={'max_digits': 'Valor Digitado passa de 100.000,00 horas verifique se digitou corretamente'}, max_digits=10, null=True, verbose_name='Quantidade de Horas 4'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='quantidade_hora5',
            field=models.DecimalField(blank=True, decimal_places=4, error_messages={'max_digits': 'Valor Digitado passa de 100.000,00 horas verifique se digitou corretamente'}, max_digits=10, null=True, verbose_name='Quantidade de Horas 5'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='quantidade_hora6',
            field=models.DecimalField(blank=True, decimal_places=4, error_messages={'max_digits': 'Valor Digitado passa de 100.000,00 horas verifique se digitou corretamente'}, max_digits=10, null=True, verbose_name='Quantidade de Horas 6'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='quantidade_hora7',
            field=models.DecimalField(blank=True, decimal_places=4, error_messages={'max_digits': 'Valor Digitado passa de 100.000,00 horas verifique se digitou corretamente'}, max_digits=10, null=True, verbose_name='Quantidade de Horas 7'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='quantidade_hora8',
            field=models.DecimalField(blank=True, decimal_places=4, error_messages={'max_digits': 'Valor Digitado passa de 100.000,00 horas verifique se digitou corretamente'}, max_digits=10, null=True, verbose_name='Quantidade de Horas 8'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='total_valor_outros',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Total Valor Outros'),
        ),
    ]
