# Generated by Django 4.1.5 on 2023-03-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_notas_quantidade_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencias',
            name='competencia',
            field=models.CharField(max_length=30, verbose_name='Competência'),
        ),
    ]
