# Generated by Django 4.1.5 on 2023-03-07 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_competencias_competencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencias',
            options={'ordering': ['competencia']},
        ),
    ]
