# Generated by Django 4.1.5 on 2023-03-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_competencias_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='contrato_texto_livre',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Contrato Texto Livre'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='texto_livre',
            field=models.CharField(blank=True, max_length=3500, null=True, verbose_name='Texto Livre'),
        ),
    ]
